/**
 * To disable the attributes of Action Requested
 */
 function disableActionRequested(disable:Boolean){
	Object__Employee__ActionRequested__HealthCvg___DMS_EMPLOYEE_ACTIONREQUESTED____HEALTH_COVERAGE.enabled = disable;
	Object__Employee__ActionRequested__HealthPrdName___DMS_EMPLOYEE_ACTIONREQUESTED____HEALTH_PRODUCT_NAME.enabled = disable;
	Object__Employee__ActionRequested__DrugCvg___DMS_EMPLOYEE_ACTIONREQUESTED____DRUG_COVERAGE.enabled = disable;
	Object__Employee__ActionRequested__DrugPrdName___DMS_EMPLOYEE_ACTIONREQUESTED____DRUG_PRODUCT_NAME.enabled = disable;
	Object__Employee__ActionRequested__DentalCvg___DMS_EMPLOYEE_ACTIONREQUESTED____DENTAL_COVERAGE.enabled = disable;
	Object__Employee__ActionRequested__DentalPrdName___DMS_EMPLOYEE_ACTIONREQUESTED____DENTAL_PRODUCT_NAME.enabled = disable;
	Object__Employee__ActionRequested__VisionCvg___DMS_EMPLOYEE_ACTIONREQUESTED____VISION_COVERAGE.enabled = disable;
	Object__Employee__ActionRequested__VisionPrdName___DMS_EMPLOYEE_ACTIONREQUESTED____VISION_PRODUCT_NAME.enabled = disable;
	Object__Employee__ActionRequested__NoOrSomeCvg___DMS_EMPLOYEE_ACTIONREQUESTED____NOORSOME_COVERAGE.enabled = disable;
	Save_ActionRequested.enabled = disable;
 }
 
 /**
  * To disable the attributes of Insurance Waiver
  */
 function disableInsuranceWaiver(disable:Boolean){
	Object__Employee__InsWaiver__WaiverSelf___DMS_EMPLOYEE_INS_WAIVER____WAIVERSELF.enabled = disable;
	Object__Employee__InsWaiver__CvgSelfHealth___DMS_EMPLOYEE_INS_WAIVER____HEALTH_SELF_COVERAGE.enabled = disable;
	Object__Employee__InsWaiver__CvgSelfDrug___DMS_EMPLOYEE_INS_WAIVER____DRUG_SELF_COVERAGE.enabled = disable;
	Object__Employee__InsWaiver__CvgSelfDental___DMS_EMPLOYEE_INS_WAIVER____DENTAL_SELF_COVERAGE.enabled = disable;
	Object__Employee__InsWaiver__CvgSelfVision___DMS_EMPLOYEE_INS_WAIVER____VISION_SELF_COVERAGE.enabled = disable;
	Object__Employee__InsWaiver__CvgSelfFDL___DMS_EMPLOYEE_INS_WAIVER____FDL_SELF_COVERAGE.enabled = disable;
	Object__Employee__InsWaiver__WaiverDependent___DMS_EMPLOYEE_INS_WAIVER____WAIVERDEPENDENT.enabled = disable;
	Object__Employee__InsWaiver__CvgDeptHealth___DMS_EMPLOYEE_INS_WAIVER____HEALTH_DEPT_COVERAGE.enabled = disable;
	Object__Employee__InsWaiver__CvgDeptDrug___DMS_EMPLOYEE_INS_WAIVER____DRUG_DEPT_COVERAGE.enabled = disable;
	Object__Employee__InsWaiver__CvgDeptDental___DMS_EMPLOYEE_INS_WAIVER____DENTAL_DEPT_COVERAGE.enabled = disable;
	Object__Employee__InsWaiver__CvgDeptVision___DMS_EMPLOYEE_INS_WAIVER____VISION_DEPT_COVERAGE.enabled = disable;
	Object__Employee__InsWaiver__WaiverDeptName1___DMS_EMPLOYEE_INS_WAIVER____WAIVER_DEPENDENT_NAME1.enabled = disable;
	Object__Employee__InsWaiver__WaiverDeptName2___DMS_EMPLOYEE_INS_WAIVER____WAIVER_DEPENDENT_NAME2.enabled = disable;
	Object__Employee__InsWaiver__WaiverDeptName3___DMS_EMPLOYEE_INS_WAIVER____WAIVER_DEPENDENT_NAME3.enabled = disable;
	Object__Employee__InsWaiver__WaiverDeptName4___DMS_EMPLOYEE_INS_WAIVER____WAIVER_DEPENDENT_NAME4.enabled = disable;
	Object__Employee__InsWaiver__WaiverDeptName5___DMS_EMPLOYEE_INS_WAIVER____WAIVER_DEPENDENT_NAME5.enabled = disable;
	Object__Employee__InsWaiver__CoverageReason___DMS_EMPLOYEE_INS_WAIVER____WAIVING_COVERAGE_REASON.enabled = disable;
	Object__Employee__InsWaiver__SelfInsCompanyName___DMS_EMPLOYEE_INS_WAIVER____SELF_INS_COMPANY_NAME.enabled = disable;
	Object__Employee__InsWaiver__CurrentHealthCvgStatus___DMS_EMPLOYEE_INS_WAIVER____CURRENT_HEALTH_CVG_STATUS.enabled = disable;
	Object__Employee__InsWaiver__OtherCoverageName___DMS_EMPLOYEE_INS_WAIVER____OTHER_COVERAGE.enabled = disable;
	Object__Employee__InsWaiver__SpouseEmpInsCompanyName___DMS_EMPLOYEE_INS_WAIVER____SPOUSE_INS_COMPANY_NAME.enabled = disable;
	Object_Customer_ActionRequested_groupCompanyName.enabled = disable;
	Object__Employee__InsWaiver__EmployeeName___DMS_EMPLOYEE_INS_WAIVER____EMPLOYEE_NAME.enabled = disable;
	Object__Employee__InsWaiver__SpouseName___DMS_EMPLOYEE_INS_WAIVER____SPOUSE_NAME.enabled = disable;
	Object__Employee__InsWaiver__EmployeeSignature___DMS_EMPLOYEE_INS_WAIVER____EMPLOYEE_SIGNATURE.enabled = disable;
	Object__Employee__InsWaiver__EmployeeSignatureEncrypted___DMS_EMPLOYEE_INS_WAIVER____EMPLOYEE_SIGNATURE_ENCRYPTED.enabled = disable;
	Object__Employee__InsWaiver__EmployeeSSNOne.enabled = disable;
	Object__Employee__InsWaiver__EmployeeSSNTwo.enabled = disable;
	Object__Employee__InsWaiver__EmployeeSSNThree.enabled = disable;
	Object__Employee__InsWaiver__SpouseSSNOne.enabled = disable;
	Object__Employee__InsWaiver__SpouseSSNTwo.enabled = disable;
	Object__Employee__InsWaiver__SpouseSSNThree.enabled = disable;
	Object__Employee__InsWaiver__month.enabled = disable;
	Object__Employee__InsWaiver__date.enabled = disable;
	Object__Employee__InsWaiver__year.enabled = disable;
	Save_InsWaiver.enabled = disable;
	Submit_InsWaive.enabled = disable;
 }
 
 /**
  * To disable the attributes of Policy Holder
  */
 function disablePolicyHolder(disable:Boolean){
	Object__Employee__PolicyHolder__LastName___DMS_EMPLOYEE____LNAME.enabled = disable;
	Object__Employee__PolicyHolder__FirstName___DMS_EMPLOYEE____FNAME.enabled = disable;
	Object__Employee__PolicyHolder__MI___DMS_EMPLOYEE____MNAME.enabled = disable;
	Object__Employee__PolicyHolder__SSNOne.enabled = disable;
	Object__Employee__PolicyHolder__SSNTwo.enabled = disable;
	Object__Employee__PolicyHolder__SSNThree.enabled = disable;
	Object__Employee__PolicyHolder__month.enabled = disable;
	Object__Employee__PolicyHolder__date.enabled = disable;
	Object__Employee__PolicyHolder__year.enabled = disable;
	Object__Employee__PolicyHolder__Gender___DMS_EMPLOYEE____GENDER.enabled = disable;
	Object__Employee__PolicyHolder__EmployementStatus___DMS_EMPLOYEE____EMPLOYMENT_STATUS.enabled = disable;
	Object__Employee__PolicyHolder__DateOfHireMonth.enabled = disable;
	Object__Employee__PolicyHolder__DateOfHireDate.enabled = disable;
	Object__Employee__PolicyHolder__DateOfHireYear.enabled = disable;
	Object__Employee__PolicyHolder__ExpirationMonth.enabled = disable;
	Object__Employee__PolicyHolder__ExpirationDate.enabled = disable;
	Object__Employee__PolicyHolder__ExpirationYear.enabled = disable;
	Object__Employee__PolicyHolder__MaritalStatus___DMS_EMPLOYEE____MARITAL_STATUS.enabled = disable;
	Object__Employee__PolicyHolder__MarriedMonth.enabled = disable;
	Object__Employee__PolicyHolder__MarriedDate.enabled = disable;
	Object__Employee__PolicyHolder__MarriedYear.enabled = disable;
	Object__Employee__PolicyHolder__MaritalStatus___DMS_EMPLOYEE____MARITAL_STATUS.enabled = disable;
	Object__Employee__PolicyHolder__JobTitle___DMS_EMPLOYEE____JOB_TITLE.enabled = disable;
	Object__Employee__PolicyHolder__DepartmentNumber___DMS_EMPLOYEE____DEPT.enabled = disable;
	Object__Employee__PolicyHolder__HomeAddress___DMS_EMPLOYEE____HOME_ADDRESS.enabled = disable;
	Object__Employee__PolicyHolder__City___DMS_EMPLOYEE____CITY.enabled = disable;
	Object__Employee__PolicyHolder__State___DMS_EMPLOYEE____STATE.enabled = disable;
	Object__Employee__PolicyHolder__Zipcode___DMS_EMPLOYEE____ZIP.enabled = disable;
	Object__Employee__PolicyHolder__EmailAddress___DMS_EMPLOYEE____EMAIL_ADDRESS1.enabled = disable;
	Object__Employee__PolicyHolder__PhoneAreaCode.enabled = disable;
	Object__Employee__PolicyHolder__AddressCode.enabled = disable;
	Object__Employee__PolicyHolder__HomeNumber.enabled = disable;
	Object__Employee__PolicyHolder__PrimaryCarePhysicam___DMS_EMPLOYEE____PRIMARY_CARE_PHYSICAN.enabled = disable;
	Save_PolicyHolders.enabled = disable;
	 
 }
 
 /**
  * To disable the attributes of Dependent
  */
 function disableDependent(disable:Boolean){
	Object__Employee__CoverageDept__Spouse__Spouse___DMS_EMPLOYEE_COVERED_SPOUSE____SPOUSE.enabled = disable;
	Object__Employee__CoverageDept__Spouse__FName___DMS_EMPLOYEE_COVERED_SPOUSE____FIRST_NAME.enabled = disable;
	Object__Employee__CoverageDept__Spouse__LName___DMS_EMPLOYEE_COVERED_SPOUSE____LAST_NAME.enabled = disable;
	Object__Employee__CoverageDept__Spouse__SSNOne.enabled = disable;
	Object__Employee__CoverageDept__Spouse__SSNTwo.enabled = disable;
	Object__Employee__CoverageDept__Spouse__SSNThree.enabled = disable;
	Object__Employee__CoverageDept__Spouse__Month.enabled = disable;
	Object__Employee__CoverageDept__Spouse__Date.enabled = disable;
	Object__Employee__CoverageDept__Spouse__Year.enabled = disable;
	Object__Employee__CoverageDept__Spouse__Gender___DMS_EMPLOYEE_COVERED_SPOUSE____GENDER.enabled = disable;
	Object__Employee__CoverageDept__Spouse__PrimaryCarePhysican___DMS_EMPLOYEE_COVERED_SPOUSE____PRIMARY_CARE_PHYSICIAN.enabled = disable;
	coveredDepend_dataGrid.enabled = disable;
	Save_CoveredDependents.enabled = disable;
	DeleteRow1.enabled = disable;	
 }
 
 /**
  * To disable the attributes of Other Coverage
  */
 function disableOtherCvg(disable:Boolean){
	Object__Employee__OtherCoverage__IsCoveredByMedicare___DMS_EMPLOYEE_OTHER_COVERAGE____COVERED_MEDICARE.enabled = disable;
	OtherCoverage_DataGrid.enabled = disable;
	AddRow_Medicare.enabled = disable;
	DeleteRow_Medicare.enabled = disable;
	Object__Employee__OtherCoverage__IsKeepingOtherHealthCoverage___DMS_EMPLOYEE_OTHER_COVERAGE____HEALTH_COVERAGE_OTHER.enabled = disable;
	Object__Employee__OtherCoverage__OtherPolicyHolderName___DMS_EMPLOYEE_OTHER_COVERAGE____OTHER_POLICYHOLDER_NAME.enabled = disable;
	Object__Employee__OtherCoverage__InsCompanyName___DMS_EMPLOYEE_OTHER_COVERAGE____INSURANCE_COMPANY_NAME.enabled = disable;
	Object__Employee__OtherCoverage__PolicyNumber___DMS_EMPLOYEE_OTHER_COVERAGE____POLICY_NUMBER.enabled = disable;
	Object__Employee__OtherCoverage__PolEffectiveDate___DMS_EMPLOYEE_OTHER_COVERAGE____OTHER_EFFECTIVE_DATE.enabled = disable;
	Object__Employee__OtherCoverage__MedicalCvg___DMS_EMPLOYEE_OTHER_COVERAGE____MEDICAL_COVERAGE.enabled = disable;
	Object__Employee__OtherCoverage__HospitalOnlyCvg___DMS_EMPLOYEE_OTHER_COVERAGE____HOSPITAL_ONLY_COVERAGE.enabled = disable;
	Object__Employee__OtherCoverage__PrescriptionDrugCvg___DMS_EMPLOYEE_OTHER_COVERAGE____PRESCRIPTION_DRUG_COVERAGE.enabled = disable;
	Object__Employee__OtherCoverage__DentalCvg___DMS_EMPLOYEE_OTHER_COVERAGE____DENTAL_COVERAGE.enabled = disable;
	Object__Employee__OtherCoverage__VisionCvg___DMS_EMPLOYEE_OTHER_COVERAGE____VISION_COVERAGE.enabled = disable;
	Object__Employee__OtherCoverage__WorkStatus___DMS_EMPLOYEE_OTHER_COVERAGE____WORK_STATUS.enabled = disable;
	Object__Employee__OtherCoverage__PolicyType___DMS_EMPLOYEE_OTHER_COVERAGE____POLICY_TYPE.enabled = disable;
	Object__Employee__OtherCoverage__IsHaveAnyPriorOrEndingCoverage___DMS_EMPLOYEE_OTHER_COVERAGE____PRIOR_ENDING_HEALTH_COVERAGE.enabled = disable;
	Object__Employee__OtherCoverage__LastEffectiveDate___DMS_EMPLOYEE_OTHER_COVERAGE____LAST_EFFECTIVE_DATE.enabled = disable;
	Object__Employee__OtherCoverage__PolicyEndDate___DMS_EMPLOYEE_OTHER_COVERAGE____POLICY_END_DATE.enabled = disable;
	Object__Employee__OtherCoverage__InsuranceCarrierName___DMS_EMPLOYEE_OTHER_COVERAGE____INSURANCE_CARRIER_NAME.enabled = disable;
	Save_OtherCoverage.enabled = disable;
	
	Object__Employee__OtherCoverage__PolEffectiveDate__Month.enabled = disable;
	Object__Employee__OtherCoverage__PolEffectiveDate__Date.enabled = disable;
	Object__Employee__OtherCoverage__PolEffectiveDate__Year.enabled = disable;
	
	Object__Employee__OtherCoverage__LastEffectiveDate__Month.enabled = disable;
	Object__Employee__OtherCoverage__LastEffectiveDate__Date.enabled = disable;
	Object__Employee__OtherCoverage__LastEffectiveDate__Year.enabled = disable;
	
	Object__Employee__OtherCoverage__PolicyEndDate__Month.enabled = disable;
	Object__Employee__OtherCoverage__PolicyEndDate__Date.enabled = disable;
	Object__Employee__OtherCoverage__PolicyEndDate__Year.enabled = disable;
	 
 }
 
  /**
   * To disable the attributes of LIC plan
   */
 function disableFortDearbornLIC(disable:Boolean){
	Object__Employee__DearBorn__BasicLifeADD___DMS_EMPLOYEE_DEARBORN____BASIC_LIFE_ADD.enabled = disable;
	Object__Employee__DearBorn__OptionalLife___DMS_EMPLOYEE_DEARBORN____OPTIONAL_LIFE.enabled = disable;
	Object__Employee__DearBorn__DependentLife___DMS_EMPLOYEE_DEARBORN____DEPENDENT_LIFE.enabled = disable;
	Object__Employee__DearBorn__LongTermDisability___DMS_EMPLOYEE_DEARBORN____LONG_TERM_DISABLITY.enabled = disable;
	Object__Employee__DearBorn__ShortTermDisablity___DMS_EMPLOYEE_DEARBORN____SHORT_TERM_DISABLITY.enabled = disable;
	Object__Employee__DearBorn__OptionalLifeAmount___DMS_EMPLOYEE_DEARBORN____OPTIONAL_LIFE_AMOUNT.enabled = disable;
	Object__Employee__DearBorn__Class___DMS_EMPLOYEE_DEARBORN____CLASS.enabled = disable;
	Object__Employee__DearBorn__AnnualSalary___DMS_EMPLOYEE_DEARBORN____ANNUAL_SALARY.enabled = disable;
	Object__Employee__DearBorn__PrimaryLastName___DMS_EMPLOYEE_DEARBORN____PRIMARY_LAST_NAME.enabled = disable;
	Object__Employee__DearBorn__PrimaryFirstName___DMS_EMPLOYEE_DEARBORN____PRIMARY_FIRST_NAME.enabled = disable;
	Object__Employee__DearBorn__PrimaryDOBMonth.enabled = disable;
	Object__Employee__DearBorn__PrimaryDOBDate.enabled = disable;
	Object__Employee__DearBorn__PrimaryDOBYear.enabled = disable;
	Object__Employee__DearBorn__PrimaryRelationship___DMS_EMPLOYEE_DEARBORN____PRIMARY_RELATIONSHIP.enabled = disable;
	Object__Employee__DearBorn__PrimaryBenefitSplit___DMS_EMPLOYEE_DEARBORN____PRIMARY_BENEFIT_SPLIT.enabled = disable;
	Object__Employee__DearBorn__SecondaryLastName___DMS_EMPLOYEE_DEARBORN____SECONDARY_LAST_NAME.enabled = disable;
	Object__Employee__DearBorn__SecondaryFirstName___DMS_EMPLOYEE_DEARBORN____SECONDARY_FIRST_NAME.enabled = disable;
	Object__Employee__DearBorn__SecondaryDOBMonth.enabled = disable;
	Object__Employee__DearBorn__SecondaryDOBDate.enabled = disable;
	Object__Employee__DearBorn__SecondaryDOBYear.enabled = disable;
	Object__Employee__DearBorn__SecondaryRelationship___DMS_EMPLOYEE_DEARBORN____SECONDARY_RELATIONSHIP.enabled = disable;
	Object__Employee__DearBorn__SecondaryBenefitSplit___DMS_EMPLOYEE_DEARBORN____SECONDARY_BENEFIT_SPLIT.enabled = disable;
	Object__Employee__DearBorn__PlanOption___DMS_EMPLOYEE_DEARBORN____PLAN_OPTION.enabled = disable;
	Save_FortDearborn.enabled = disable;
	 
 }
 
 /**
  * To disable the attributes of MedicalHealth
  */
 function disableMedicalHealth(disable:Boolean){
	explanationPopUpWindow.popupDG.enabled=disable;
    explanationPopUpWindow.btnSave.enabled=disable;
	Object__Employee__MedicalQuestion__NameSelf___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____SELF_NAME.enabled = disable;
	Object__Employee__MedicalQuestion__NameSpouse___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____SPOUSE_NAME.enabled = disable;
	Object__Employee__MedicalQuestion__HeightSelf___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____SELF_HEIGHT.enabled = disable;
	Object__Employee__MedicalQuestion__HeightSpouse___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____SPOUSE_HEIGHT.enabled = disable;
	Object__Employee__MedicalQuestion__WeightSelf___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____SELF_WEIGHT.enabled = disable;
	Object__Employee__MedicalQuestion__WeightSpouse___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____SPOUSE_WEIGHT.enabled = disable;
	Object__Employee__MedicalQuestion__SmokerSelf___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____SELF_SMOKER.enabled = disable;
	Object__Employee__MedicalQuestion__SmokerSpouse___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____SPOUSE_SMOKER.enabled = disable;
	dependent_DataGrid.enabled = disable;
	Object__Employee__MedicalCondition__Cancer___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____CANCER.enabled = disable;
	Object__Employee__MedicalCondition__Leukemia___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____LEUKEMIA.enabled = disable;
	Object__Employee__MedicalCondition__Lymphoma___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____LYMPHOMA.enabled = disable;
	Object__Employee__MedicalCondition__Chemotherapy___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____CHEMOTHERAPY.enabled = disable;
	Object__Employee__MedicalCondition__Radiation___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____RADIATION.enabled = disable;
	Object__Employee__MedicalCondition__CancerType___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____CANCER_TYPE.enabled = disable;
	Object__Employee__MedicalCondition__LeukemiaType___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____LEUKEMIA_TYPE.enabled = disable;
	Object__Employee__MedicalCondition__LymphomaType___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____LYMPHOMA_TYPE.enabled = disable;
	Object__Employee__MedicalCondition__Allergies___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____ALLERGIES.enabled = disable;
	Object__Employee__MedicalCondition__Shots___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____SHOTS.enabled = disable;
	Object__Employee__MedicalCondition__Asthma___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____ASTHMA.enabled = disable;
	Object__Employee__MedicalCondition__CysticFibrosis___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____CYSTICFIBROSIS.enabled = disable;
	Object__Employee__MedicalCondition__Emphysema___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____EMPHYSEMA.enabled = disable;
	Object__Employee__MedicalCondition__LungOther___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____LUNG_OTHER.enabled = disable;
	Object__Employee__MedicalCondition__Oxygen___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____OXYGEN.enabled = disable;
	Object__Employee__MedicalCondition__LungOtherIsAny___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____LUNG_OTHERISANY.enabled = disable;
	Object__Employee__MedicalCondition__DegenerativeDiscDisease___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____DEGENERATIVE_DISC_DISEASE.enabled = disable;
	Object__Employee__MedicalCondition__Fibromyalgia___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____FIBROMYALGIA.enabled = disable;
	Object__Employee__MedicalCondition__HerniatedDisc___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____HERNIATED_DISC.enabled = disable;
	Object__Employee__MedicalCondition__OsteoArthritis___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____OSTEO_ARTHRITIS.enabled = disable;
	Object__Employee__MedicalCondition__RheumatoidArthritis___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____RHEUMATOIDARTHRITIS.enabled = disable;
	Object__Employee__MedicalCondition__JointReplacement___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____JOINT_REPLACEMENT.enabled = disable;
	Object__Employee__MedicalCondition__MuscularOther___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____MUSCULAR_OTHER.enabled = disable;
	Object__Employee__MedicalCondition__MuscularOtherIsAny___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____MUSCULAR_OTHERISANY.enabled = disable;
	Object__Employee__MedicalCondition__Aneurysm___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____ANEURYSM.enabled = disable;
	Object__Employee__MedicalCondition__CADAngina___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____CADANGINA.enabled = disable;
	Object__Employee__MedicalCondition__Angioplasty___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____ANGIOPLASTY.enabled = disable;
	Object__Employee__MedicalCondition__BypassSurgery___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____BYPASS_SURGERY.enabled = disable;
	Object__Employee__MedicalCondition__CongestiveHeartFailure___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____CONGESTIVE_HEART_FAILURE.enabled = disable;
	Object__Employee__MedicalCondition__HeartAttack___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____HEARTATTACK.enabled = disable;
	Object__Employee__MedicalCondition__PacemakerICD___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____PACEMAKER_ICD.enabled = disable;
	Object__Employee__MedicalCondition__Stroke___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____STROKE.enabled = disable;
	Object__Employee__MedicalCondition__BloodClot___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____BLOODCLOT.enabled = disable;
	Object__Employee__MedicalCondition__IrregularHeartBeat___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____IRREGULAR_HEARTBEAT.enabled = disable;
	Object__Employee__MedicalCondition__PeripheralVascular___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____PERIPHERAL_VASCULAR.enabled = disable;
	Object__Employee__MedicalCondition__Anemia___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____ANEMIA.enabled = disable;
	Object__Employee__MedicalCondition__OtherBloodDisorder___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____OTHERBLOOD_DISORDER.enabled = disable;
	Object__Employee__MedicalCondition__Hypertension___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____HYPER_TENSION.enabled = disable;
	Object__Employee__MedicalCondition__HighCholesterol___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____HIGHCHOLESTEROL.enabled = disable;
	Object__Employee__MedicalCondition__HeartValveDisorder___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____HEART_VALVE_DISORDER.enabled = disable;
	Object__Employee__MedicalCondition__HeartOther___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____HEART_OTHER.enabled = disable;
	Object__Employee__MedicalCondition__AneurysmType___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____ANEURYSM_TYPE.enabled = disable;
	Object__Employee__MedicalCondition__AngioplastyDateMonth.enabled = disable;
	Object__Employee__MedicalCondition__AngioplastyDateDate.enabled = disable;
	Object__Employee__MedicalCondition__AngioplastyDateYear.enabled = disable;
	Object__Employee__MedicalCondition__BypassSurgeryDateMonth.enabled = disable;
	Object__Employee__MedicalCondition__BypassSurgeryDateDate.enabled = disable;
	Object__Employee__MedicalCondition__BypassSurgeryDateYear.enabled = disable;
	Object__Employee__MedicalCondition__HeartAttackDateMonth.enabled = disable;
	Object__Employee__MedicalCondition__HeartAttackDateDate.enabled = disable;
	Object__Employee__MedicalCondition__HeartAttackDateYear.enabled = disable;
	Object__Employee__MedicalCondition__StrokeDateMonth.enabled = disable;
	Object__Employee__MedicalCondition__StrokeDateDate.enabled = disable;
	Object__Employee__MedicalCondition__StrokeDateYear.enabled = disable;
	Object__Employee__MedicalCondition__AnemiaType___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____ANEMIA_TYPE.enabled = disable;
	Object__Employee__MedicalCondition__OtherBloodDisorderType___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____OTHERBLOOD_DISORDER_TYPE.enabled = disable;
	Object__Employee__MedicalCondition__BPReading1___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____BPREADING1.enabled = disable;
	Object__Employee__MedicalCondition__BPReading2___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____BPREADING2.enabled = disable;
	Object__Employee__MedicalCondition__BPReading3___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____BPREADING3.enabled = disable;
	Object__Employee__MedicalCondition__HeartOtherIsAny___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____HEART_OTHER_IS_ANY.enabled = disable;
	Object__Employee__MedicalCondition__DiabetesInsulin___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____DIABETES_INSULIN.enabled = disable;
	Object__Employee__MedicalCondition__DiabetesOral___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____DIABETES_ORAL.enabled = disable;
	Object__Employee__MedicalCondition__DiabetesDietExercise___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____DIABETES_DIET_EXERCISE.enabled = disable;
	Object__Employee__MedicalCondition__ThyroidDisorder___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____THYROID_DISORDER.enabled = disable;
	Object__Employee__MedicalCondition__EndocrineOther___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____ENDOCRINE_OTHER.enabled = disable;
	Object__Employee__MedicalCondition__BSRdgsHGB1___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____BS_RDGS_HGB1.enabled = disable;
	Object__Employee__MedicalCondition__BSRdgsHGB2___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____BS_RDGS_HGB2.enabled = disable;
	Object__Employee__MedicalCondition__BSRdgsHGB3___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____BS_RDGS_HGB3.enabled = disable;
	Object__Employee__MedicalCondition__EndocrineOtherIsAny___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____ENDOCRINE_OTHER_IS_ANY.enabled = disable;
	Object__Employee__MedicalCondition__CerebralPalsy___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____CEREBRAL_PALSY.enabled = disable;
	Object__Employee__MedicalCondition__Epilepsy___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____EPILEPSY.enabled = disable;
	Object__Employee__MedicalCondition__MultipleSclerosis___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____MULTIPLE_SCLEROSIS.enabled = disable;
	Object__Employee__MedicalCondition__ParkinsonDisease___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____PARKINSON_DISEASE.enabled = disable;
	Object__Employee__MedicalCondition__NeurologicalOther___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____NEUROLOGICAL_OTHER.enabled = disable;
	Object__Employee__MedicalCondition__NeurologicalMal___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____NEUROLOGICAL_MAL.enabled = disable;
	Object__Employee__MedicalCondition__DateofLastSeizureMonth.enabled = disable;
	Object__Employee__MedicalCondition__DateofLastSeizureDate.enabled = disable;
	Object__Employee__MedicalCondition__DateofLastSeizureYear.enabled = disable;
	Object__Employee__MedicalCondition__NeurologicalOtherIsAny___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____NEUROLOGICAL_OTHER_ISANY.enabled = disable;
	Object__Employee__MedicalCondition__DepressionAnxiety___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____DEPRESSION_ANXIETY.enabled = disable;
	Object__Employee__MedicalCondition__BipolorSchizophrenia___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____BIPOLOR_SCHIZOPHRENIA.enabled = disable;
	Object__Employee__MedicalCondition__Hospitalized___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____HOSPITALIZED.enabled = disable;
	Object__Employee__MedicalCondition__SuicideAttempt___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____SUICIDE_ATTEMPT.enabled = disable;
	Object__Employee__MedicalCondition__PsychologicalOther___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____PSYCHOLOGICAL_OTHER.enabled = disable;
	Object__Employee__MedicalCondition__HospitalizedDateMonth.enabled = disable;
	Object__Employee__MedicalCondition__HospitalizedDateDate.enabled = disable;
	Object__Employee__MedicalCondition__HospitalizedDateYear.enabled = disable;
	Object__Employee__MedicalCondition__SuicideAttemptMonth.enabled = disable;
	Object__Employee__MedicalCondition__SuicideAttemptDate.enabled = disable;
	Object__Employee__MedicalCondition__SuicideAttemptYear.enabled = disable;
	Object__Employee__MedicalCondition__PsychologicalIsAny___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____PSYCHOLOGICAL_OTHER_ISANY.enabled = disable;
	Object__Employee__MedicalCondition__AbnormalPap___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____ABNORMAL_PAP.enabled = disable;
	Object__Employee__MedicalCondition__NormalFollowupPap___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____NORMAL_FOLLOWUP_PAP.enabled = disable;
	Object__Employee__MedicalCondition__ColonPolypsDiverticulitis___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____COLON_POLYPS_DIVERTICULITIS.enabled = disable;
	Object__Employee__MedicalCondition__CrohnUlcerativeColitis___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____CROHN_ULCERATIVE_COLITIS.enabled = disable;
	Object__Employee__MedicalCondition__GastricRefluxUlcer___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____GASTRIC_REFLUX_ULCER.enabled = disable;
	Object__Employee__MedicalCondition__EnlargedProstate___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____ENLARGED_PROSTATE.enabled = disable;
	Object__Employee__MedicalCondition__KidneyStones___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____KIDNEY_STONES.enabled = disable;
	Object__Employee__MedicalCondition__InfertilitityTreatments___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____INFERTILITITY_TREATMENTS.enabled = disable;
	Object__Employee__MedicalCondition__PolycysticOvarianSyndrome___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____POLYCYSTIC_OVARIAN_SYNDROME.enabled = disable;
	Object__Employee__MedicalCondition__Endometriosis___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____ENDOMETRIOSIS.enabled = disable;
	Object__Employee__MedicalCondition__UrinaryOther___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____URINARY_OTHER.enabled = disable;
	Object__Employee__MedicalCondition__AbnormalPapDateMonth.enabled = disable;
	Object__Employee__MedicalCondition__AbnormalPapDateDate.enabled = disable;
	Object__Employee__MedicalCondition__AbnormalPapDateYear.enabled = disable;
	Object__Employee__MedicalCondition__NormalFollowupPapDateMonth.enabled = disable;
	Object__Employee__MedicalCondition__NormalFollowupPapDateDate.enabled = disable;
	Object__Employee__MedicalCondition__NormalFollowupPapDateYear.enabled = disable;
	Object__Employee__MedicalCondition__UrinaryOtherIsAny___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____URINARY_OTHER_ISANY.enabled = disable;
	Object__Employee__MedicalCondition__EndStageRenalFailure___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____ENDSTAGE_RENAL_FAILURE.enabled = disable;
	Object__Employee__MedicalCondition__Transplant___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____TRANSPLANT.enabled = disable;
	Object__Employee__MedicalCondition__HIV___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____HIV.enabled = disable;
	Object__Employee__MedicalCondition__Hemophilia___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____HEMOPHILIA.enabled = disable;
	Object__Employee__MedicalCondition__Lupus___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____LUPUS.enabled = disable;
	Object__Employee__MedicalCondition__Hepatitis___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____HEPATITIS.enabled = disable;
	Object__Employee__MedicalCondition__MiscOther___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____MISC_OTHER.enabled = disable;
	Object__Employee__MedicalCondition__TransplantType___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____TRANSPLANT_TYPE.enabled = disable;
	Object__Employee__MedicalCondition__LupusType___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____LUPUS_TYPE.enabled = disable;
	Object__Employee__MedicalCondition__HepatitisType___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____HEPATITIS_TYPE.enabled = disable;
	Object__Employee__MedicalCondition__MiscOtherIsany___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____MISC_OTHER_ISANY.enabled = disable;
	Object__Employee__MedicalQuestion__DiseaseTreatedBefore___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____DISEASE_TREATED_BEFORE.enabled = disable;
	Object__Employee__MedicalQuestion__OperatedHospitalizedBefore___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____OPERATED_HOSPITALIZED_BEFORE.enabled = disable;
	Object__Employee__MedicalQuestion__AdvisedFurtherTreatment___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____ADVISED_FURTHER_TREATMENT.enabled = disable;
	Object__Employee__MedicalQuestion__CurrentlyPregnant___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____CURRENTLY_PREGNANT.enabled = disable;
	Object__Employee__MedicalQuestion__AnyMedication___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____ANY_MEDICATION.enabled = disable;
	Object__Employee__MedicalQuestion__WorkerCompensation___DMS_EMPLOYEE_MED_HEALTH_QUESTIONNAIRE____WORKER_COMPENSATION.enabled = disable;
	explanation_dataGrid.enabled = disable;
	AddRow.enabled = disable;
	DeleteRow.enabled = disable;
	Save_MedicalHealth.enabled = disable;
	
 }
 
  /**
   * To disable the attributes of About your needs
   */
 function disableAboutYourNeeds(disable:Boolean){
	Object__Employee__AboutNeeds__HearingImpaired___DMS_EMPLOYEE_OTHER_NEEDS____HEARING_IMPAIRED.enabled = disable;
	Object__Employee__AboutNeeds__VisionImpaired___DMS_EMPLOYEE_OTHER_NEEDS____VISION_IMPAIRED.enabled = disable;
	Object__Employee__AboutNeeds__IsOtherPrimaryLanguage___DMS_EMPLOYEE_OTHER_NEEDS____ISOTHER_PRIMARY_LANGUAGE.enabled = disable;
	Object__Employee__AboutNeeds__IsOtherCulturalNeed___DMS_EMPLOYEE_OTHER_NEEDS____ISOTHER_CULTURAL_NEED.enabled = disable;
	Object__Employee__AboutNeeds__OtherPrimaryLanguage___DMS_EMPLOYEE_OTHER_NEEDS____OTHER_PRIMARY_LANGUAGE.enabled = disable;
	Object__Employee__AboutNeeds__OtherCulturalNeed___DMS_EMPLOYEE_OTHER_NEEDS____OTHER_CULTURAL_NEED.enabled = disable;
	Save_AboutYourNeeds.enabled = disable;	
 }
 
  /**
   * To disable the attributes of Terms and Condition
   */
 function disableTermsAndCondition(disable:Boolean){
	Object__Employee__TermsAndCondition__EmployeeSignature___DMS_EMPLOYEE____EMPLOYEE_SIGNATURE.enabled = disable;
	Object__Employee__TermsAndCondition__EmployeeSignatureEncrypted___DMS_EMPLOYEE____EMPLOYEE_SIGNATURE_ENCRYPTED.enabled = disable;
	Object__Employee__TermsAndCondition__EmployeeSubmittedDate___DMS_EMPLOYEE____EMPLOYEE_SUBMITTED_DATE.enabled = disable;
	Object__Employee__TermsAndCondition__SpouseSignature___DMS_EMPLOYEE____EMPLOYEE_SPOUSE_SIGNATURE.enabled = disable;
	Object__Employee__TermsAndCondition__SpouseSignatureEncrypted___DMS_EMPLOYEE____EMPLOYEE_SPOUSE_SIGNATURE_ENCRYPTED.enabled = disable;
	Object__Employee__TermsAndCondition__SpouseSubmittedDate___DMS_EMPLOYEE____EMPLOYEE_SPOUSE_SUBMITTED_DATE.enabled = disable;
	Save_Terms_Condition.enabled = disable;
	submit_TermsNCondition.enabled = disable;	
 }
 
 /**
  * To disable the attributes of Validation
  */
 function freezeTab(tabName:String) {

	 if(employeeApplicationStatus=="E_SUBMITTED"){		
		if(tabName=="PolicyHolder"){
			disablePolicyHolder(false);
		}else if(tabName=="CoveredDependent"){
			disableDependent(false);
		}else if(tabName=="OtherCoverage"){
			disableOtherCvg(false);	
		}else if(tabName=="FortDearbornLIC"){
			disableFortDearbornLIC(false);
		}else if(tabName=="MedHealth"){
			disableMedicalHealth(false);
		}else if(tabName=="AboutYourNeeds"){
			disableAboutYourNeeds(false);
		}else if(tabName=="TermsAndCondition"){
			disableTermsAndCondition(false);
		}		
	 }
 }
 
  //TO Freeze the Tab for WAIVER SUBMITTED STATUS
  function freezeTabForWaiver(tabName:String) {
	 if(employeeInsWaiverStatus=="WAIVER_SUBMITTED" || employeeInsWaiverStatus=="E_SUBMITTED"){		
		if(tabName=="ActionRequested"){
			disableActionRequested(false);
		}else if(tabName=="InsuranceWaiver"){
			disableInsuranceWaiver(false);
		}		
	 }
 }
 
 /**
  * To hide the indicator image (tick and wrong image)
  */
  function hideIndicatorImage(){
	 // informationMessage = Alert.show("Hide img"+(!enableIndicator || !enableIndicatorInsWaiver), "Information", Alert.OK , this, myclickHandler, "stockIcon", Alert.OK);		
	  //informationMessage.move(450,500);
	if(!enableIndicator && !enableIndicatorInsWaiver){
		action_wrong._visible=false;
		action_wrong1._visible=false;
		action_right._visible=false;
		action_right1._visible=false;
		insWaiver_wrong._visible=false;
		insWaiver_wrong1._visible=false;
		insWaiver_right._visible=false;
		insWaiver_right1._visible=false;
		
	}

	if(!enableIndicator){
		
		policyHolder_wrong._visible=false;
		policyHolder._visible=false;
		policyHolder_right._visible=false;
		policyHolderRight._visible=false;
		covered_wrong._visible=false;
		covered_right._visible=false;		
		otherCoverage_wrong._visible=false;
		other_wrong._visible=false;
		otherCoverage_right._visible=false;
		other_right._visible=false;		
		dearBorn_right._visible=false;
		dearBorn_wrong._visible=false;		
		medicalQues_wrong._visible=false;
		medicalQues_right._visible=false;		
		aboutYourNeeds_wrong._visible=false;
		aboutYourNeeds_right._visible=false;		
		pre_existing_right._visible=false;		
		terms_right._visible=false;  
	}
  }
  
  /**
  * To show the indicator image (tick and wrong image)
  */
  function showIndicatorImage(){

	action_wrong._visible=true;
	action_wrong1._visible=true;
	action_right._visible=true;
	action_right1._visible=true;
	insWaiver_wrong._visible=true;
	insWaiver_wrong1._visible=true;
	insWaiver_right._visible=true;
	insWaiver_right1._visible=true;
	policyHolder_wrong._visible=true;
	policyHolder._visible=true;
	policyHolder_right._visible=true;
	policyHolderRight._visible=true;
	covered_wrong._visible=true;
	covered_right._visible=true;		
	otherCoverage_wrong._visible=true;
	other_wrong._visible=true;
	otherCoverage_right._visible=true;
	other_right._visible=true;		
	dearBorn_right._visible=true;
	dearBorn_wrong._visible=true;		
	medicalQues_wrong._visible=true;
	medicalQues_right._visible=true;		
	aboutYourNeeds_wrong._visible=true;
	aboutYourNeeds_right._visible=true;		
	pre_existing_right._visible=true;		
	terms_right._visible=true;  
  }
  
  function showInsWaiverIndicatorImage(){

	action_wrong._visible=true;
	action_wrong1._visible=true;
	action_right._visible=true;
	action_right1._visible=true;
	insWaiver_wrong._visible=true;
	insWaiver_wrong1._visible=true;
	insWaiver_right._visible=true;
	insWaiver_right1._visible=true;
  }
  
  function displayInsWaiverImage(){
	if(enableIndicatorInsWaiver){
		if(isActionRequested){
			action_wrong._visible = false;
			action_wrong1._visible = false;
		}else{
			action_wrong._visible = true;
			action_wrong1._visible = true;
		}
		if(isInsWaiver){			
			insWaiver_wrong._visible = false;
			insWaiver_wrong1._visible = false;
		}else{
			insWaiver_wrong._visible = true;
			insWaiver_wrong1._visible = true;
		}
	}
	
  }